# tell travis we need cpy of docker running

sudo: required
services:
  - docker

before_install:
  - docker build -t jerryc96/docker-react -f Dockerfile.dev .

# used to exec test suite
script:
  - docker run jerryc96/docker-react npm run test -- --coverage